name: qsmnet2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - astor=0.7.1
  - attrs=19.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.1.5
  - c-ares=1.15.0
  - ca-certificates=2025.8.3
  - certifi=2024.8.30
  - cffi=1.14.0
  - cloudpickle=1.4.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.19.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gast=0.3.3
  - git=2.23.0
  - glib=2.65.0
  - gmp=6.1.2
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - imageio=2.8.0
  - importlib-metadata=1.6.1
  - importlib_metadata=1.6.1
  - intel-openmp=2020.1
  - ipykernel=5.3.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_contrib_core=0.3.3
  - jupyter_core=4.6.3
  - jupyter_latex_envs=1.4.6
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - krb5=1.18.2
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.4
  - nibabel=3.1.1
  - ninja=1.9.0
  - notebook=5.7.10
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.1.1
  - prometheus_client=0.10.0
  - prompt-toolkit=3.0.5
  - protobuf=3.12.3
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pydicom=2.0.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.7.1
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - readline=8.0
  - scikit-image=0.16.2
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=47.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.32.3
  - tensorboardx=2.5.1
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.3
  - wcwidth=0.2.4
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
      - cachetools==5.2.0
      - charset-normalizer==2.1.1
      - fastmri==0.1.1
      - fsspec==2022.8.2
      - future==0.18.2
      - google-auth==2.12.0
      - google-auth-oauthlib==0.4.6
      - idna==3.4
      - numpy==1.21.6
      - oauthlib==3.2.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pytictoc==1.5.1
      - pytorch-lightning==1.0.8
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - runstats==2.0.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-determinism==0.3.0
      - torchsummary==1.5.1
      - torchvision==0.13.1
      - tqdm==4.64.1
      - urllib3==1.26.12
prefix: /home/chungseok/.conda/envs/qsmnet2
